# fly.toml app configuration file generated for delicate-paper-7097 on 2023-08-10T17:12:07+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-paper-7097"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
